version: "3.7"

services:
    app:
      build:
        context: ../..
        dockerfile: Dockerfile
      image: app-node
      container_name: gerador-de-sistemas-front-app
      ports:
        - "8080:80"