version: "3.7"

services:
  app:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: app-php81
    container_name: app-gerador-de-sistemas-back
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - project-network

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx-gerador-de-sistemas-back
    restart: always
    ports:
      #- "80:80"
      - "9001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - project-network


networks:
  project-network:
    driver: bridge













#version: '3'
#
#services:
#  php8.1:
#    image: php:8.1
#    container_name: php8.1
#    ports:
#      - 9001:80
#    restart: always
#    volumes:
#      - /var/www/html:/var/www/html
#    links:
#      - db80


# Imagem Mysql Versão 8.0
#db80:
#  image: mysql:8.0
#  container_name: mysql8.0
#  command: --default-authentication-plugin=mysql_native_password
#  restart: always
#  ports:
#    - 3380:3306
#  environment:
#    - MYSQL_ROOT_PASSWORD=root
#  volumes:
#    - ./data-mysql-80:/var/lib/mysql
